version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      # Point your app at the mongo container
      MONGO_URI: mongodb://mongo:27017/sms
      # Use the same port inside & outside
      PORT: 3000
      # Bring in sensitive values from your host .env
      JWT_SECRET: ${JWT_SECRET}
      SMTP_HOST:  ${SMTP_HOST}
      SMTP_PORT:  ${SMTP_PORT}
      SMTP_USER:  ${SMTP_USER}
      SMTP_PASS:  ${SMTP_PASS}
      SMTP_SECURE:${SMTP_SECURE}
      SMTP_FROM:  ${SMTP_FROM}
      LOG_LEVEL:  ${LOG_LEVEL}
    command: npm run dev

volumes:
  mongo-data:
